### PR TITLE
Bugfix: prevent double prefix in route cache

### LINKED ISSUE #68: Prefixed routes are malformed after route:cache command
**Describe the bug**

When one registers a route with a prefix and the route:cache command has been executed then the registered route uri becomes malformed; the prefix is duplicated and the locale is gone.

**Steps to Reproduce**

Register prefixed route
```php
Route::prefix('prefix')->group(function() {

    Route::multilingual('/test-route', fn() => 'Test Route')
        ->name('test-route');

});
```

```bash
php artisan route:cache
php artisan route:list --name=test-route
```
 
**Reproduction output**
```bash
php artisan route:list --name=test-route
+--------+----------+----------------------+---------------+---------+------------+
| Domain | Method   | URI                  | Name          | Action  | Middleware |
+--------+----------+----------------------+---------------+---------+------------+
|        | GET|HEAD | en/prefix/test-route | en.test-route | Closure |            |
|        | GET|HEAD | fr/prefix/test-route | fr.test-route | Closure |            |
|        | GET|HEAD | nl/prefix/test-route | nl.test-route | Closure |            |
|        | GET|HEAD | sv/prefix/test-route | sv.test-route | Closure |            |
+--------+----------+----------------------+---------------+---------+------------+
```

```bash
php artisan route:cache
Route cache cleared!
Routes cached successfully!
```

```bash
php artisan route:list --name=test-route
+--------+----------+--------------------------+---------------+---------+------------+
| Domain | Method   | URI                      | Name          | Action  | Middleware |
+--------+----------+--------------------------+---------------+---------+------------+
|        | GET|HEAD | prefix/prefix/test-route | nl.test-route | Closure |            |
|        | GET|HEAD | prefix/prefix/test-route | en.test-route | Closure |            |
|        | GET|HEAD | prefix/prefix/test-route | fr.test-route | Closure |            |
|        | GET|HEAD | prefix/prefix/test-route | sv.test-route | Closure |            |
+--------+----------+--------------------------+---------------+---------+------------+
```

```bash
php artisan route:clear
Route cache cleared!
```

```bash
php artisan route:list --name=test-route
+--------+----------+----------------------+---------------+---------+------------+
| Domain | Method   | URI                  | Name          | Action  | Middleware |
+--------+----------+----------------------+---------------+---------+------------+
|        | GET|HEAD | en/prefix/test-route | en.test-route | Closure |            |
|        | GET|HEAD | fr/prefix/test-route | fr.test-route | Closure |            |
|        | GET|HEAD | nl/prefix/test-route | nl.test-route | Closure |            |
|        | GET|HEAD | sv/prefix/test-route | sv.test-route | Closure |            |
+--------+----------+----------------------+---------------+---------+------------+
```

**Additional context**

PHP 8.1
Laravel 8.X
Branch v2

### PR DESCRIPTION
**Pull request by ghost**
Fixes #68

Routes that are registered by Laravel's route registrar don't contain the prefix in the cached routes file and the ones by the package do.

This MR removes the prefix from the route's action payload after registering so once it's being serialized there's no referral left to the original prefix. The URI is at that point in time already prefixed.

I looked into your test and can't seem to find any point where you test cached routes so I'm not really sure how to write a test for this and if it even should be tested in the package since its framework behavior.

### CODE REVIEW

File: src/MultilingualRegistrar.php [hunk 1]
```diff
@@ -166,6 +166,10 @@ protected function generateRoute(string $key, $handle, string $locale, array $op
                 ->defaults('headers', Arr::get($options, 'headers', []));
         }
 
+        if (filled($route->action['prefix'] ?? null)) {
+            $route->action['prefix'] = null;
```
Comment (chinleung) [inline src/MultilingualRegistrar.php]: Can't we simply remove the `if` case since we will be setting it to null ?

Comment (ghost) [reply src/MultilingualRegistrar.php]: Agreed
